# Generated by Django 3.1.4 on 2020-12-09 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_reply'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reply',
            name='reply_post',
        ),
        migrations.AddField(
            model_name='reply',
            name='reply_post',
            field=models.ManyToManyField(null=True, to='blog.Post'),
        ),
    ]
